Validating found git in: git
git から Git 2.17.1 を使用しています
Opening repository for path='/home/itolab-chotaro/HDD/Python/メカトロ/ex1' failed; ex=Failed to execute git {
  "exitCode": 128,
  "gitErrorCode": "NotAGitRepository",
  "gitCommand": "rev-parse",
  "stdout": "",
  "stderr": "fatal: not a git repository (or any parent up to mount point /home/itolab-chotaro)\nStopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).\n"
}
Opening repository for path='/home/itolab-chotaro/HDD/Python/メカトロ/ex1' failed; ex=Failed to execute git {
  "exitCode": 128,
  "gitErrorCode": "NotAGitRepository",
  "gitCommand": "rev-parse",
  "stdout": "",
  "stderr": "fatal: not a git repository (or any parent up to mount point /home/itolab-chotaro)\nStopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).\n"
}
Opening repository for path='/home/itolab-chotaro/HDD/Python/メカトロ/ex1/client.py' failed; ex=Error: spawn ENOTDIR
Opening repository for path='/home/itolab-chotaro/HDD/Python/メカトロ/ex1/server.py' failed; ex=Error: spawn ENOTDIR
Opening repository for path='/home/itolab-chotaro/HDD/Python/メカトロ/ex1' failed; ex=Failed to execute git {
  "exitCode": 128,
  "gitErrorCode": "NotAGitRepository",
  "gitCommand": "rev-parse",
  "stdout": "",
  "stderr": "fatal: not a git repository (or any parent up to mount point /home/itolab-chotaro)\nStopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).\n"
}
Opening repository for path='/home/itolab-chotaro/HDD/Python/メカトロ/ex1' failed; ex=Failed to execute git {
  "exitCode": 128,
  "gitErrorCode": "NotAGitRepository",
  "gitCommand": "rev-parse",
  "stdout": "",
  "stderr": "fatal: not a git repository (or any parent up to mount point /home/itolab-chotaro)\nStopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).\n"
}
